server:
  port: 9903

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://xielin002:a123456@192.168.0.4:9900/eureka/

spring:
  application:
    name: zuul-service
  cloud:
    loadbalancer:
      retry:
        enabled: false
zuul:
  routes:
    server:
      path: /server/**
      serviceId: server-service
      sensitiveHeaders: "*"
    web:
      path: /web/**
      serviceId: web-service
      sensitiveHeaders: "*"
