server:
  port: 9900

eureka:
  instance:
    hostname: rhs-cloud
  client:
    #     声明是否将自己的信息注册到 Eureka 服务器上
    registerWithEureka: false
    #     是否到 Eureka 服务器中抓取注册信息
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://xielin002:a123456@192.168.0.4:9900/eureka/


spring:
  application:
    name: eurka-service
  security:
    user:
      name: xielin002
      password: a123456